spring:
  application:
    name: peer-study

# This is the configuration for the datasource. We are using PostgreSQL as our database, and we need to provide the connection details such as URL, username, password, and driver class name.
# Note that in a real application, we would typically use environment variables or a secure vault to store sensitive information like database credentials, rather than hardcoding them in the configuration file.
# Create postres database with name "mylocaldb" and user "mylocaldb" with password "mylocaldb" before running the application Otherwise COMMENT OUT the datasource configuration below to avoid connection errors.
# Incase no Local PostgreSQL database is available, Comment this datasource and removed the dependency for PostgreSQL driver in the pom.xml file to avoid connection errors.

#  datasource:
#    url: jdbc:postgresql://localhost:5432/mylocaldb
#    username: mylocaldb
#    password: mylocaldb
#    driver-class-name: org.postgresql.Driver

# For Docker Compose when appliction runnning inside the container, look up the database connection details from environment variables and use them to configure the datasource.
# This allows the application to connect to the PostgreSQL database running in the "db" service defined in the docker-compose.yml file without hardcoding the connection details in the configuration file. Make sure to set the environment variables SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, and SPRING_DATASOURCE_PASSWORD in the docker-compose.yml file as shown in the example above.
  datasource:
    url: jdbc:postgresql://db:5432/peer_study_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# This is the server configuration. We set the port to 8081, but this can be changed if needed.
# The default is 8080, but we want to avoid conflicts with other services that might be running on the same port.
server:
  port: 8081

# This is for actuator endpoints, which are used for health checks and metrics. We want to expose all of them for now, but we can restrict this later if needed.
# By default, only a few endpoints are exposed, so we need to explicitly include all of them. This is useful for monitoring and debugging purposes.
management:
  endpoints:
    web:
      exposure:
        include: "*"
    # This is the base path for all actuator endpoints. By default, it's "/actuator", but we can change it if we want to have a different structure for our API.
    # For example, we could set it to "/monitoring" if we want to have
    # all monitoring-related endpoints under a common path. For now, we'll keep it as "/actuator".
    base-path: /actuator
    prometheus:
      enabled: true

