# f you are using Docker Desktop v4.52+ (which uses Docker Engine v29+), the default API version has increased to 1.44.
# Older versions of Testcontainers (v1.20 and below) might fail to handshake.
api.version=1.44
