-- Create table for ProductEntity (@Table(name = "products"))
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION
);

-- Create table for MobileEntity (@Table(name = "mobiles"))
CREATE TABLE IF NOT EXISTS mobiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(255),
    model VARCHAR(255)
);